# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_auto_20171219_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='print',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
