# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_auto_20171220_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ManyToManyField(default=-1, related_name='image', to='merch.Print')),
                ('image_size', models.ManyToManyField(default=-1, related_name='cart_img_size', to='merch.Size')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='merch.Cart'),
        ),
    ]
