# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_auto_20171221_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='print',
            name='description',
        ),
        migrations.RemoveField(
            model_name='print',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='print',
            name='name',
        ),
        migrations.RemoveField(
            model_name='print',
            name='size',
        ),
        migrations.AddField(
            model_name='cart',
            name='print_item',
            field=models.ManyToManyField(related_name='print_link', to='merch.Print'),
        ),
        migrations.AddField(
            model_name='print',
            name='print_size',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='size_link', to='merch.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='print_image',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='img_link', to='merch.Image'),
            preserve_default=False,
        ),
    ]
